#!/bin/sh

mkdir -p -v results/$1/everystep
mkdir -p -v results/$1/netcdf
mkdir -p -v results/$1/time_series
mkdir -p -v results/$1/hourly
mkdir -p -v results/$1/monthly
mkdir -p -v results/$1/daily

# Modifying driver file
sed -i '2d' driver_file.dat
sed -i "\$a setup/$1_driver.dat" driver_file.dat

# Modifying setup file
sed -i '2d' setup_file.dat
sed -i "\$a setup/$1_setup.dat" setup_file.dat 

file=./setup/$1_setup.dat
if [ ! -f ${file} ];
then
	echo "Warning: The file ${file} does not exist"
fi

file=./setup/$1_driver.dat
if [ ! -f ${file} ];
then
	echo "Warning: The file ${file} does not exist"
fi

file=./data/$1.dat
if [ ! -f ${file} ];
then
	echo "Warning: The file ${file} does not exist"
fi

